server:
  host: 0.0.0.0
  port: 8083
  debug: false
picon:
  width: 1024
  height: 1024
  background: transparent
sources:
  logos_dir: ./logos
  github_sources:
  - name: MarhyCZ/picons
    repo: MarhyCZ/picons
    path: '1024'
    enabled: true
    token: ''
  - name: luvadcz/piconsserver
    repo: luvadcz/piconsserver
    path: ''
    enabled: true
    token: ''
  remote:
    enabled: false
    url: ''
  picon_cz:
    username: ''
    password: ''
    enabled: false
own_github:
  enabled: false
  repo: ''
  path: '1024'
  token: ''
  commit_prefix: 'Picon: '
cache:
  disk_dir: ./cache
  dnu_v_kesi: 7
  memory_lru_size: 200
services:
  skylink:
    name_patterns: []
xbmc_kodi:
  username: ''
  password: ''
  cookies_file: ''
